package bio

import scala.io.Source

object VibrioCholerae {
  val filename = "data/vibrio_cholerae.txt"
  lazy val code = new LoadGenome(filename).genome

  def main(args: Array[String]): Unit = {
    println(s"VibrioCholerae length: ${code.length}")

    /*
    val input = Source.fromFile("data/test.txt").getLines.mkString.split(" ")
    val genome = input(0)
    val pattern = input(1)

    println(KMer.count(genome, pattern))
    */

    /*
    val g = "TACAATGATACAATGAGGGCCCGCGTCGCTCGTCGCTCACGCAATCACGCAATGTTAATGATCACGCAATCACGCAATGTTAATGATGGGCCCGGTTAATGATCGTCGCTCACGCAATTACAATGAGGGCCCGCACGCAATCACGCAATGGGCCCGGGGCCCGCGTCGCTGTTAATGATCGTCGCTCGTCGCTTACAATGAGGGCCCGTACAATGAGTTAATGATTACAATGAGGGCCCGGGGCCCGCGTCGCTCACGCAATCACGCAATGGGCCCGCACGCAATCGTCGCTCGTCGCTCGTCGCTCACGCAATGTTAATGATTACAATGATACAATGACGTCGCTTACAATGACACGCAATCACGCAATCGTCGCTTACAATGACACGCAATTACAATGACGTCGCTTACAATGAGGGCCCGTACAATGAGTTAATGATCGTCGCTCACGCAATTACAATGAGTTAATGATCACGCAATTACAATGACGTCGCTTACAATGATACAATGACGTCGCTCACGCAATGGGCCCGCGTCGCTGGGCCCGGTTAATGATCGTCGCTGTTAATGATTACAATGATACAATGAGGGCCCGCGTCGCTCGTCGCTCGTCGCTCGTCGCTCACGCAATCACGCAATCACGCAATGTTAATGATCACGCAATGTTAATGATTACAATGAGTTAATGATTACAATGACACGCAATGGGCCCGGGGCCCGGGGCCCGCACGCAATGTTAATGATTACAATGACACGCAATTACAATGACGTCGCTCACGCAATCACGCAATTACAATGACACGCAATGTTAATGATCACGCAATGGGCCCGTACAATGA"
    val f = 14
    KMer.mostFrequent(g, f).foreach(println)
    */

    /*
    val input = Source.fromFile("data/test.txt").getLines.mkString
    println(KMer.reverseCompliment(input))
    */

    val input = Source.fromFile("data/vibrio_cholerae.txt").getLines.mkString
    val output = KMer.matchPattern(input, "CTTGATCAT").mkString(" ")
    println(output)
  }
}

class LoadGenome(filename: String) {
  lazy val genome = Source.fromFile(filename).getLines.mkString
}
